---

- name: Copy postfix regular expression checks.
  copy: src={{item.src}} dest={{item.dest}} owner=root group=root mode=644
  with_items:
    - { src: 'postfix/header_checks', dest: '/etc/postfix/header_checks' }
    - { src: 'postfix/body_checks', dest: '/etc/postfix/body_checks' }
    - { src: 'postfix/helo_restrictions', dest: '/etc/postfix/helo_restrictions' }

- name: Copy postfix main configuration.
  template: src=postfix/main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=644

- name: Copy postfix master configuration.
  copy: src=postfix/master.cf dest=/etc/postfix/master.cf owner=root group=root mode=644 backup=yes

- name: Copy mailname.
  template: src=postfix/mailname.j2 dest=/etc/mailname owner=root group=root mode=644

- name: Copy postfix virtual mailbox mapping.
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=644
  with_items:
    - { src: 'postfix/mysql-virtual-alias-maps.cf.j2', dest: '/etc/postfix/mysql-virtual-alias-maps.cf' }
    - { src: 'postfix/mysql-virtual-mailbox-domains.cf.j2', dest: '/etc/postfix/mysql-virtual-mailbox-domains.cf' }
    - { src: 'postfix/mysql-virtual-mailbox-maps.cf.j2', dest: '/etc/postfix/mysql-virtual-mailbox-maps.cf' }

- name: Whitelist policyd IPs from No-IP backup SMTP.
  lineinfile: dest=/etc/apache2/conf-available/security.conf regexp="^skip_addresses " line="skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1,8.23.224.50,69.65.5.119,69.65.5.110" state=present
