---

- name: Set ServerSignature.
  ansible.builtin.lineinfile:
    dest: /etc/apache2/extra/httpd-default.conf
    regexp: "^ServerSignature "
    line: "ServerSignature Off"
    state: present

- name: Set ServerTokens.
  ansible.builtin.lineinfile:
    dest: /etc/apache2/extra/httpd-default.conf
    regexp: "^ServerTokens "
    line: "ServerTokens Prod"
    state: present

- name: Check for deflate module.
  ansible.builtin.stat:
    path: /etc/apache2/mods-enabled/deflate.load
  register: mod_deflate

# Deflate is an "essential" module, requiring forced disable.
- name: Disable deflate module to mitigate BREACH attack.
  ansible.builtin.command: /usr/sbin/a2dismod -f deflate
  when: mod_deflate.stat.exists

- name: Disable CGI module.
  apache2_module:
    state: absent
    name: cgi
